name: 编译lede源码
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: '此处输入release发行说明:'
        default: '用户未填写'

env:
  REPO_URL: https://github.com/1774293824/lede
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 检出源码到workflows
      uses: actions/checkout@main
    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo -e "$(nproc) 个核心编译"      
        echo -e "首次初始化环境完成,运行df -Th 命令:"
        df -Th                
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL        
        echo -e "首次运行删除无用文件命令,预计清理完成后可用空间为37G.已完成删除无用文件,运行df -Th 命令:"
        df -Th          
        sudo docker image prune --all --force
        echo -e "第二次运行删除无用docker文件命令,预计清理完成后可用空间为40G.已完成删除无用docker镜像,运行df -Th 命令:"
        df -Th        
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq full-upgrade -y
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 克隆源代码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b master openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 加载自定义订阅源
      run: |
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: 更新feeds订阅源
      run: cd openwrt && ./scripts/feeds update -a

    - name: 安装feeds订阅源
      run: cd openwrt && ./scripts/feeds install -a

    - name: 加载自定义配置的.sh文件
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: 下载 dl 库
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8

    - name: 编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) 个核心编译"
        make -j$(nproc)
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        TZ="Asia/Shanghai" echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 检查磁盘使用情况
      if: (!cancelled())
      run: df -hT

    - name: 进入/bin/targets目录下,先删除packages文件夹,再将当前路径写入变量
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        ll
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传/bin/targets目录中的产物至 Actions 下载页
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: 生成发布标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y-%m-%d_%H.%M")" >> $GITHUB_OUTPUT
        touch release_notes.txt
        echo "status=success" >> $GITHUB_OUTPUT
        echo "${{ github.event.inputs.release_notes }}" >> release_notes.txt
        echo "让我们再来看看release_notes.txt中是什么内容:"
        echo "$(cat release_notes.txt)"

    - name: 上传固件到release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release_notes.txt
        files: ${{ env.FIRMWARE }}/*
